### PR TITLE
Update to blog UI

### PR DESCRIPTION
**Pull request by eatonphil**
screen shot 2016-11-15 at 9 21 24 pm
screen shot 2016-11-15 at 9 21 32 pm

### CODE REVIEW

**Comment by eatonphil** [comment]
The screenshots here are out of date. Here is the latest:

screen shot 2017-01-03 at 4 02 19 pm
screen shot 2017-01-03 at 4 02 32 pm
screen shot 2017-01-03 at 4 02 51 pm

**Comment by rmcintosh** [comment]
I like the lighter weight on "Engineering" a lot -- maybe could up letter-spacing just a tiny, tiny bit to make it feel a little less squished with the thinner lines?

**Comment by eatonphil** [comment]
@rmcintosh Good idea.

**Comment by eatonphil** [comment]
screen shot 2017-01-03 at 4 35 01 pm

**Comment by rmcintosh** [comment]
👍 nice! lookin' good

**Comment by mparke** [comment]
Good looking stuff. some suggestions in a pull against your branch, @eatonphil https://github.com/eatonphil/linode-blog/pull/1

**Comment by eatonphil** [comment]
Few updates based on suggestions by @rmcintosh and @mparke:

screen shot 2017-01-03 at 5 17 42 pm

**Comment by eatonphil** [comment]
Hmm. After staring at it for a bit, the h1 on the listing page looks gigantic. Here is a screenshot using h2 instead:

screen shot 2017-01-03 at 5 20 33 pm

**Comment by eatonphil** [comment]
I just noticed the code sections have no indication they are code sections right now. So added a border around them:

screen shot 2017-01-03 at 5 24 15 pm

**Comment by eatonphil** [comment]
Tightened up each post header as suggested by @mparke

screen shot 2017-01-03 at 5 33 30 pm

**Comment by eatonphil** [comment]
screen shot 2017-01-03 at 5 35 36 pm
screen shot 2017-01-03 at 5 35 53 pm

**Comment by Dorthu** [comment]
Looks good.  Only thing I'd suggest is making the author portraits line up - it looks unorganized having them spread around horizontally as they are here.  Maybe switching the portrait and the author name is enough to achieve this?

**Comment by eatonphil** [comment]
@Dorthu could we just drop the portraits?

**Comment by eatonphil** [comment]
screen shot 2017-01-04 at 11 04 58 am

**Comment by briansteffens** [comment]
Better yet, make them all pictures of me. And make a big image of my face follow the mouse cursor around. And make the background me too.

**Comment by eatonphil** [comment]
screen shot 2017-01-04 at 11 05 24 am

**Comment by Dorthu** [comment]
@eatonphil I guess, but I like them.  I don't think it'd be that hard to line them up.

**Comment by briansteffens** [comment]
That does look a lot cleaner without the portraits. Lining them up or giving them stronger borders may help.

**Comment by eatonphil** [comment]
@Dorthu yeah it's not hard, it just didn't look that great in a different way to me.

screen shot 2017-01-04 at 11 06 38 am

**Comment by eatonphil** [comment]
I still prefer the no image personally, but there you go.

**Comment by na3d** [comment]
Yeah, I prefer no image, as beautiful as our team is.

**Comment by scub** [comment]
I'd +1 no images.

**Comment by illblew** [comment]
👍

**Comment by na3d** [comment]
Screens? :)

**Comment by RobertDeRose** [comment]
@eatonphil if i get time, i'll make a pr against this branch

**Comment by na3d** [comment]
I am merging this, because a lot was accomplished with this PR.  Also because I like the ship early and ship often philosophy.

**Pull request merged**
